import 'dart:convert';
import 'dart:io';

const _defaultBaselinePath = 'tool/analyzer_baseline.txt';
const _analyzeArgs = <String>[
  'analyze',
  '--no-fatal-infos',
  '--no-fatal-warnings',
  '--no-pub',
];

final _issuePattern = RegExp(
  r'^\s*(info|warning|error)\s+•\s+(.*?)\s+•\s+(.+?):(\d+):(\d+)\s+•\s+([a-zA-Z0-9_]+)\s*$',
);

Future<void> main(List<String> args) async {
  final updateBaseline = args.contains('--update-baseline');
  final baselinePath = _readOption(args, '--baseline') ?? _defaultBaselinePath;

  final result = await Process.run(
    'flutter',
    _analyzeArgs,
    runInShell: true,
  );

  final rawOutput = [
    if ((result.stdout as String).isNotEmpty) result.stdout as String,
    if ((result.stderr as String).isNotEmpty) result.stderr as String,
  ].join('\n');

  final issues = LineSplitter.split(rawOutput)
      .map(_AnalyzerIssue.tryParse)
      .whereType<_AnalyzerIssue>()
      .toList()
    ..sort();

  if (result.exitCode != 0 && issues.isEmpty) {
    stderr
      ..writeln('Failed to run flutter analyze.')
      ..writeln(rawOutput.trim());
    exit(result.exitCode);
  }

  final baselineFile = File(baselinePath);
  if (updateBaseline) {
    await baselineFile.parent.create(recursive: true);
    final sink = StringBuffer()
      ..writeln('# Flutter analyzer baseline')
      ..writeln(
          '# Generated by `dart run tool/analyze_with_baseline.dart --update-baseline`')
      ..writeln('# One issue per line: level|code|path|line|column|message');
    for (final issue in issues) {
      sink.writeln(issue.serialize());
    }
    await baselineFile.writeAsString(sink.toString());
    stdout.writeln(
      'Updated $baselinePath with ${issues.length} baseline issue(s).',
    );
    return;
  }

  if (!baselineFile.existsSync()) {
    stderr.writeln(
      'Baseline file not found at $baselinePath. '
      'Run `dart run tool/analyze_with_baseline.dart --update-baseline` first.',
    );
    exit(1);
  }

  final baselineEntries = LineSplitter.split(await baselineFile.readAsString())
      .map((line) => line.trim())
      .where((line) => line.isNotEmpty && !line.startsWith('#'))
      .toSet();
  final currentEntries = issues.map((issue) => issue.serialize()).toSet();

  final newIssues = currentEntries.difference(baselineEntries).toList()..sort();
  final resolvedIssues = baselineEntries.difference(currentEntries).toList()
    ..sort();

  stdout.writeln(
    'Analyzer baseline check: ${issues.length} current issue(s), '
    '${baselineEntries.length} baseline issue(s).',
  );

  if (newIssues.isNotEmpty) {
    stderr.writeln('New analyzer issues detected (${newIssues.length}):');
    for (final issue in newIssues) {
      stderr.writeln(issue);
    }
    exit(1);
  }

  if (resolvedIssues.isNotEmpty) {
    stdout.writeln(
      'Resolved ${resolvedIssues.length} baseline issue(s). '
      'Refresh the baseline when convenient.',
    );
  }

  stdout.writeln('No new analyzer issues detected.');
}

String? _readOption(List<String> args, String name) {
  for (final arg in args) {
    if (arg.startsWith('$name=')) {
      return arg.substring(name.length + 1);
    }
  }
  return null;
}

final class _AnalyzerIssue implements Comparable<_AnalyzerIssue> {
  const _AnalyzerIssue({
    required this.level,
    required this.message,
    required this.path,
    required this.line,
    required this.column,
    required this.code,
  });

  final String level;
  final String message;
  final String path;
  final int line;
  final int column;
  final String code;

  static _AnalyzerIssue? tryParse(String line) {
    final match = _issuePattern.firstMatch(line);
    if (match == null) return null;
    return _AnalyzerIssue(
      level: match.group(1)!,
      message: match.group(2)!,
      path: match.group(3)!,
      line: int.parse(match.group(4)!),
      column: int.parse(match.group(5)!),
      code: match.group(6)!,
    );
  }

  String serialize() => '$level|$code|$path|$line|$column|$message';

  @override
  int compareTo(_AnalyzerIssue other) {
    return serialize().compareTo(other.serialize());
  }
}
